"""empty message

Revision ID: 8df9865d27e9
Revises: 502d45217c2f
Create Date: 2022-03-04 13:17:17.314900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df9865d27e9'
down_revision = '502d45217c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'state')
    # ### end Alembic commands ###
