"""message ralationship update

Revision ID: a95227aa8f54
Revises: 0900cb663289
Create Date: 2022-03-10 15:03:07.862942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a95227aa8f54'
down_revision = '0900cb663289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['user_id'])
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
