"""table product_orders cascade delete

Revision ID: aac490b5d600
Revises: deb4734dc193
Create Date: 2022-03-09 16:23:27.313289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac490b5d600'
down_revision = 'deb4734dc193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_orders_product_id_fkey', 'products_orders', type_='foreignkey')
    op.create_foreign_key(None, 'products_orders', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_orders', type_='foreignkey')
    op.create_foreign_key('products_orders_product_id_fkey', 'products_orders', 'products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
