"""message relationship update

Revision ID: ac2c3150fa88
Revises: 0900cb663289
Create Date: 2022-03-10 14:25:30.145405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac2c3150fa88'
down_revision = '0900cb663289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('messages', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
