"""table product_orders cascade delete on order_id FK

Revision ID: b03432a77432
Revises: aac490b5d600
Create Date: 2022-03-09 16:26:31.170790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03432a77432'
down_revision = 'aac490b5d600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_orders_order_id_fkey', 'products_orders', type_='foreignkey')
    op.create_foreign_key(None, 'products_orders', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_orders', type_='foreignkey')
    op.create_foreign_key('products_orders_order_id_fkey', 'products_orders', 'orders', ['order_id'], ['order_id'])
    # ### end Alembic commands ###
